version: "3"
services:
  
  # PostgreSQL
  db:
    build:
      dockerfile: ./docker/db.dockerfile
      context: .
    container_name: netbox_db
    restart: always  
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
    ports:
      - "5432:5432"
    networks:
      - netbox_network
    volumes:
      - /var/lib/postgresql:/var/lib/postgresql
      - ./config/netbox_config_db.sh:/docker-entrypoint-initdb.d/netbox_config_db.sh

  # Netbox
  app:
    build:
      dockerfile: ./docker/python.dockerfile
      context: .
    container_name: netbox_app
    restart: always
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
    ports:
      - "8000:8000"
    networks:
      - netbox_network
    volumes:
      - ./config/init.sh:/docker-entrypoint/init.sh
    depends_on:
      - "db"
    
  # NGINX
  web:
    image: nginx:latest
    container_name: netbox_web
    restart: always
    ports:
      - "80:80"
    networks:
      - netbox_network
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - "app"



networks:
  netbox_network:
    driver: bridge
