version: "3"
services:
  
  # PostgreSQL
  db:
    build:
      dockerfile: ./docker/db.dockerfile
      context: .
    container_name: netbox_db
    restart: always  
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      NETBOX_PASSWORD: "${NETBOX_PASSWORD}"
    ports:
      - "5432:5432" 
    networks:
      - netbox_network
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
      - ./config/netbox_config_db.sh:/docker-entrypoint-initdb.d/netbox_config_db.sh

  # Netbox
  app:
    build:
      dockerfile: ./docker/python.dockerfile
      context: .
    container_name: netbox_app
    restart: always
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      NETBOX_PASSWORD: "${NETBOX_PASSWORD}"
    ports:
      - "8000:8000"
    networks:
      - netbox_network
    volumes:
      - ./config/init.sh:/docker-entrypoint/init.sh
    depends_on:
      - "db"
    
  # NGINX
  web:
    image: nginx:latest
    container_name: netbox_web
    restart: always
    ports:
      - "80:80"
    networks:
      - netbox_network
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./backup_webapp:/backup_webapp
    depends_on:
      - "app"
  
  # Backup APP
  backup:
    build:
      context: .
      dockerfile: ./docker/backup.dockerfile
    container_name: netbox_backup
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      NETBOX_PASSWORD: "${NETBOX_PASSWORD}"
    ports:
      - "5000:5000"
    restart: always
    networks:
      - netbox_network
    volumes:
      - ./backup_app:/app
      - /var/lib/postgresql/dumps:/pg_dumps
    depends_on:
      - "db"



networks:
  netbox_network:
    driver: bridge
